### ISSUE TITLE
Add Glazed Builder to lightning_dxpr, from private repo

### ISSUE THREAD

**Issue by jjroelofs** [jjroelofs/lightning_dxpr#2]
I see on the official composer website that it's possible to check out private github repositories if your machine has access to them:
https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md

Can you update the lightning_dxpr profile do download and enable the following additional items:

- Glazed Theme (8.x branch)
- Glazed Builder (8.x branch)
- Glazed Helper (latest release on drupal.org)
- Field Group (latest 3.x release on drupal.org)

- enable glazed_builder_page module (include in glazed_builder/modules)
- skip installing core layout builder module and Lightning content types using it (is that possible?)

I know this will make the package impossible to install for people without github access but for now I can really use this for automated testing. We can later figure out how to let composer install with or without Glazed Builder, depending on some access API, or split up into 2 profiles.

**Comment by dench0** [comment]
@jjroelofs 
I checked how to create private repositories and now me need:
1. new git repository for satis
2. hosting accessible from the web where that private repositories will store.

**Comment by jjroelofs** [comment]
Hi Denis, why do you not just use our current Glazed Builder repo? That article mentions that Github can be used.

**Comment by dench0** [comment]
@jjroelofs If you thoroughly read the [Setup](https://getcomposer.org/doc/articles/handling-private-packages-with-satis.md#setup) section in that article, you will see that github uses only as a source for the satis composer repositories, but to fetch that repositories by composer you need own web server.

**Comment by jjroelofs** [comment]
Got it. I checked out some of the docs. If I give you a fresh VPS how many hours do you think it will take to set everything up? (rough estimation)

**Comment by dench0** [comment]
Wait maybe better for now is just using ssh keys, in that keys we can use private repository as any other https://getcomposer.org/doc/05-repositories.md#using-private-repositories

**Comment by jjroelofs** [comment]
what are the disadvantages to this simpler solution? I guess it will not dynamically download the latest stable version? Let's do it anyways since it is simple and we need to learn all the possibilities

**Comment by jjroelofs** [comment]
@see https://github.com/jjroelofs/glazed_builder/pull/653
